export const SET_LANGUAGE = 'SET_LANGUAGE';
export const LOAD_EMPLOYEES = 'LOAD_EMPLOYEES';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';